### ISSUE TITLE
Deploy hcloud-cloud-controller-manager

### ISSUE THREAD

**Issue by thetechnick** [xetys/hetzner-kube#4]
Hi,
nice tool you have built!

To integrate the kubernetes cluster with the Hetzner Cloud API you might also want to deploy the [hcloud-cloud-controller-manger](https://github.com/hetznercloud/hcloud-cloud-controller-manager).
As you are already using `kubeadm` the deployment instructions should be easy to adapt: https://github.com/hetznercloud/hcloud-cloud-controller-manager#deployment

**Comment by xetys** [comment]
hey! I've already seen this project a few days ago...I will take a look at this ASAP to integrate the cloud controller manager with hetzner-kube

**Comment by xetys** [comment]
ok, I did the first try.

@thetechnick could you please review the current state? I indeed deletes the node if I delete it in the console. But I don't see any metadata on the nodes...

**Comment by thetechnick** [comment]
@xetys Only 2 small issues:
1. You need to call `systemctl daemon-reload` after adding the `20-hcloud.conf` drop in file.
2. The drop in needs to be present on all nodes not only the master

After fixing those manually after cluster creation, deleting one of the nodes `kubectl delete no my-cluster-worker-01` and restarting the kubelet on the node. The node is properly initialized by the cloud-controller-manager:

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2018-01-31T16:12:44Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: cx11
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: nbg1
    failure-domain.beta.kubernetes.io/zone: nbg1-dc3
    kubernetes.io/hostname: my-cluster-worker-01
```
