### ISSUE TITLE
can we also add kubernetes-dashboard as addon

### ISSUE THREAD

**Issue by quorak** [xetys/hetzner-kube#83]
I think this would be of great value, to get a quick overview over the newly created cluster.

**Comment by xetys** [comment]
Unfortunately this is a hard piece. I did a production setup last week and spent hours of making it work with let's encrypt certificates...

**Comment by radutopala** [comment]
Maybe these below will help some. I'm sure these can be automated, as in `minikube`, without the need of fully installing `cert-manager` etc.

Managed to install and get into the dashboard using the following.

I am storing the kube config in a `config` file in the local folder, therefore all `kubectl` run with `--kubeconfig config`.

A. install
```
kubectl --kubeconfig config apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```
B. confirm install
```
kubectl --kubeconfig config get svc --namespace kube-system
```
C. create `admin-user.yaml` (https://github.com/kubernetes/dashboard/wiki/Creating-sample-user#create-service-account) and apply it
`admin-user.yaml`:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
```
run:
```
kubectl --kubeconfig config --namespace kube-system apply -f admin-user.yaml
```
D. create `admin-user-cluster-role.yaml` (https://github.com/kubernetes/dashboard/wiki/Creating-sample-user#create-clusterrolebinding) and apply it
`admin-user-cluster-role.yaml`:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
```
run:
```
kubectl --kubeconfig config --namespace kube-system apply -f admin-user-cluster-role.yaml
```
E. describe the secret for the admin-user and get the token:
```
kubectl --kubeconfig config --namespace kube-system describe secret $(kubectl --kubeconfig config --namespace kube-system get secret | grep admin-user | awk '{print $1}')
```
copy the token..
F. run the proxy
```
kubectl --kubeconfig config --namespace kube-system proxy
```
G. go to http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login, select Token and enter the copied token. You should now be in, granted with full access, as in a `minikube` dashboard.
